server:
  port: 8002
spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #优先使用ip地址的方式注册
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}
    appname: ${spring.application.name}