server:
  port: 8000
spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false #注册中心集群化时改为true 用于服务间互相注册
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 60000 #清理服务器